include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    shield: hummingbird rgbled_widget
  - board: seeeduino_xiao_ble
    shield: totem_right
    shield: hummingbird rgbled_widget
# there is no settingsreset (needed) for the XIAO
