include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart # zmk studio
  - board: seeeduino_xiao_ble
    shield: totem_right
  #- board: seeeduino_xiao_ble
  #  shield: totem_dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset