include:
  - board: seeeduino_xiao_ble
    shield: totem_left #rgbled_widget
  - board: seeeduino_xiao_ble
    shield: totem_right #rgbled_widget
# there is no settingsreset (needed) for the XIAO
  - board: seeeduino_xiao_ble
    shield: settings_reset
