include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: hummingbird rgbled_widget
# there is no settingsreset (needed) for the XIAO
